# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRYKbFDdciofNdvKH3vGMZCPXHpUi1Xj
"""

import pandas as pd
baza={
    "Fish":["Topilova Abrora"," Xolmatova Jumagul", "TOjiyeva Roziya"," Alimboyeva Fotima", "Valiyeva Shahlo","Valiyeva Ozoda", "Aliyev Mustafo","Salimov Sardor","Qodirov Muhammadjon"," Ergashev Dilshod"],
    "Yosh":[ "17","16", "15"," 18", "14", "13", "12", "10", "18", "11" ],
    "Maktabi":["9-maktab", "2-maktab", "3-maktab", "5-maktab", "6-maktab", "8-maktab", "1-maktab", "4-maktab", "10-maktab", "36-maktab"],
    "Jinsi":["ayol","ayol","ayol","ayol","ayol","ayol","erkak","erkak","erkak","erkak",],
    "Manzili":[ "Farg'ona shahar", "Andijon shahar","Samarqand viloyati", "Furqat tumani", "Namangan viloyati", "Buxoro Viloyati", "Xorazm viloyati", "Navoiy viloyati", "Dang'ara tumani", "Shaxrixon tumani"]
}
malumot=pd.DataFrame(baza)
print(malumot)

filtr=malumot[malumot['Jinsi']=='erkak']
print(filtr)